name: Destroy Azure Environmnet

on:
  workflow_dispatch:
    
env:
  AZURE_RESOURCE_GROUP: cd-with-actions3
  AZURE_APP_PLAN: actions-ttt-deployment
  AZURE_LOCATION: '"UK West"'
  AZURE_WEBAPP_NAME: test-ttt-app3
  
jobs:
    destroy-azure-resources:
    runs-on: ubuntu-latest
  
    if: contains(github.event.pull_request.labels.*.name, 'destroy environment')
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
        
      - name: destroy Azure environmnet
        if: success()
        run: |
          az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --yes
